### ISSUE TITLE
Data availability?

### ISSUE THREAD

**Issue by PabloBotas** [deniando/VARPP#1]
Hi,
Very nice work on this repository and the publication. I was wondering if you have scripts to transform the contents of the `.RData` files in the supplemental materials into VCF files. I was interested in recalculating the results with the current Exomiser version and getting these data would be very helpful.

Any ideas?

Best,
Pablo

**Comment by deniando** [comment]
Hi Pablo

Thanks, I’m afraid I do not have scripts to transform the contents of the .RData files to vcf files. I think bcftools has functionality to transform text files into vcf files, so you may be able to extract the relevant columns and try this.

Thanks

Denise

**Comment by PabloBotas** [comment]
Hi,
Thanks, yes, I'll give it a try. Alternatively I could simply try to download the data directly from ClinVar.

Best,
Pablo
